missionChip color get expertMissionChips 
ds_3_snip_20_s55 
s55 
missionChip 
getDefaultConfiguration getDefaultScreenDevice getLocalGraphicsEnvironment GraphicsEnvironment gc GraphicsConfiguration 
gc color expertMission loadMissionChip 
expertMission 
