TIMESTAMP Types registerColumnType 
VARBINARY Types registerColumnType 
NUMERIC Types registerColumnType 
BLOB Types registerColumnType 
CLOB Types registerColumnType 
USE_STREAMS_FOR_BINARY Environment setProperty getDefaultProperties 
STATEMENT_BATCH_SIZE Environment DEFAULT_BATCH_SIZE setProperty getDefaultProperties 
StandardSQLFunction registerFunction 
BIT Types registerColumnType 
StandardSQLFunction registerFunction 
BIGINT Types registerColumnType 
StandardSQLFunction registerFunction 
SMALLINT Types registerColumnType 
STRING StandardBasicTypes StandardSQLFunction registerFunction 
TINYINT Types registerColumnType 
StandardSQLFunction registerFunction 
INTEGER Types registerColumnType 
STRING StandardBasicTypes StandardSQLFunction registerFunction 
CHAR Types registerColumnType 
TIMESTAMP StandardBasicTypes StandardSQLFunction registerFunction 
VARCHAR Types registerColumnType 
TIMESTAMP StandardBasicTypes NoArgSQLFunction registerFunction 
FLOAT Types registerColumnType 
DOUBLE Types registerColumnType 
ds_6_snip_2$HibernateORM_TimesTenDialect 
TimesTenDialect 
TIMESTAMP StandardBasicTypes NoArgSQLFunction registerFunction 
StandardSQLFunction registerFunction 
DATE Types registerColumnType 
TIME Types registerColumnType 
